### PR TITLE
see if this will fix the linux build

### PR DESCRIPTION
**Pull request by haikusw**
just guessing. see if travis will run and validate

### CODE REVIEW

**Comment by haikusw** [comment]
Hmm.  Travis not running.  Maybe have to say "ready for review" first?  I'll try that.

**Comment by haikusw** [comment]
Guess Travis isn't setup to run on PRs before they are merged (that's unfortunate if so), or the message about travis domain name ("Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on") means something in this project's settings I can't see needs to be edited.

**Comment by helje5** [comment]
Yes, Travis is off, this should just move to GH Actions.

**Comment by helje5** [comment]
Tried to setup GH Actions, may need some more work :-) Probably needs some testing w/o GH Actions first.

**Pull request closed without merging**
